[tool]
[tool.poetry]
authors=["Robert Sandfield <rsandfield@github.com>"]
name="root"
version="0.0.0"
description="A bot to help manage things"

[tool.poetry.dependencies]
python="^3.8"
flask="^2.0"
discord="^1.7"